### ISSUE TITLE
breaking changes with parcel v2

### ISSUE THREAD

**Issue by Marvin9** [nano-react-app/template-js#16]
<img width="1440" alt="Screenshot 2021-08-14 at 11 42 00 PM" src="https://user-images.githubusercontent.com/17699717/129456509-0d3b5e37-75c6-4e72-bb99-8b2409f2c9af.png">

As mentioned, `type="module"` inside `script` tag of `index.html` will fix the issue.

**Comment by mgreasly** [comment]
Closing this issue as we're not using parcel now, and we've added the type-"module" as part of the shift to ViteJS.
