### ISSUE TITLE
Can not import images 

### ISSUE THREAD

**Issue by ivanbkovacevic** [nano-react-app/template-js#3]
Hello,

Me again  :)  

I have a problem with uploading images. I tried to import it like this - import logo from "../logo.svg";  and I tried to set a path directly in image tag but it does not upload images.

Does someone have a solution?

**Comment by adrianmcli** [comment]
I'd give this plugin a shot: https://github.com/albinotonnina/parcel-plugin-inlinesvg

Just remember that this is basically just a Parcel app. So any documentation you find for Parcel will just work.

**Comment by ivanbkovacevic** [comment]
I try it and does not work. I have problems with all type of images not just svg.

**Comment by adrianmcli** [comment]
Have a look at this example? https://github.com/jaredpalmer/react-parcel-example

Also how about this plugin? https://github.com/smooth-code/svgr/tree/master/packages/parcel-plugin-svgr

**Comment by ivanbkovacevic** [comment]
It does not work. I think that initially something is wrong with react-nano parcel configuration

**Comment by adrianmcli** [comment]
Can you put up a reproduction repo on Github and I can take a look?
