### ISSUE TITLE
Does not work with private npm repositories

### ISSUE THREAD

**Issue by tirthaguha** [nano-react-app/template-js#6]
Hi, 

`nano-react-app` does not work with private npm proxy repositories. 
Upon investigation, it seems that its a problem with this template. The template gets downloaded fine, but then it tries to run npm install in the directory, and npm install fails because of presence or package-lock.json. will raise a PR soon.

**Comment by adrianmcli** [comment]
I assume this should be fixed now?

**Comment by tirthaguha** [comment]
This works as expected now. Thanks.
