### ISSUE TITLE
/src/App.js: transform-react-jsx: pragma has been set but pragmaFrag has not been set

### ISSUE THREAD

**Issue by LGmatrix13** [nano-react-app/template-js#8]
When I imported the template I received the following error
`/src/App.js: transform-react-jsx: pragma has been set but pragmaFrag has not been set
`

**Comment by adrianmcli** [comment]
@LGmatrix13 can you try again? I don't think this should be a problem anymore.

**Comment by LGmatrix13** [comment]
Yes, I'll try again. Thanks for responding!

**Comment by mgreasly** [comment]
Given this was over a year ago, I'm going to assume it's not an issue any more and close this issue.
